icons_format = "{icon}"

# https://github.com/greshake/i3status-rust/blob/v0.32.0/doc/themes.md
[theme]
theme = "dracula"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

## [[block]]
## block = "disk_space"
## path = "/"
## info_type = "available"
## alert_unit = "GB"
## interval = 20
## warning = 20.0
## alert = 10.0
## format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
good = 60.0
warning = 50.0
critical = 30.0

[[block]]
block = "temperature"
chip = "coretemp-isa-0000"
format = " $icon $max max "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "keyboard_layout"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y-%d-%m %R') "
