#!/bin/bash

# fix plasma/dolphin apps list
export XDG_MENU_PREFIX=plasma-

# screen locking facility
which xss-lock &>/dev/null && \
  xss-lock --transfer-sleep-lock -- /opt/ivanko/bin/lock-session &

# compose key
which setxkbmap &> /dev/null && \
  setxkbmap -option compose:ralt &

# network manager applet
which nm-applet &> /dev/null && \
  nm-applet &
